### PR TITLE
Use HTTP GET request for acquiring family information

### LINKED ISSUE #33: Bibliographic data missing from OPS family response
Dear George,

some users and the lovely people from @Patent2Net reported that family responses from OPS stopped yielding bibliographic information for some weeks already. This broke some features of Patent2Net [2] as well as PatZilla [3].

As outlined on [1], it looks like only POST requests would fail while GET requests would still succeed.

With kind regards,
Andreas.

[1] https://meta.ip-tools.org/t/bibliographic-data-missing-from-ops-family-response/161
[2] https://github.com/Patent2net/P2N-v3
[3] https://github.com/ip-tools/ip-navigator

### PR DESCRIPTION
**Pull request by amotl**
Dear George,

we've outlined the background for this update at #33 and humbly ask you to create a patch release if this resonates with you.

Thanks already and with kind regards,
Andreas.

### CODE REVIEW

**Comment by amotl** [comment]
Dear @gsong,

this update is rather important to the [PatZilla](https://github.com/ip-tools/ip-navigator) and [Patent2Net](https://github.com/patent2net/) communities.

The updated functionality is secured by additional unit tests, so we are pretty sure things won't go south.

So, we are humbly asking if you could review the update and make a release on PyPI. Thank you so much for taking the time!

With kind regards,
Andreas.

**Comment by gsong** [comment]
@amotl Arg, why doesn't GitHub send me notifications when a PR is opened!? I'll take a look at this shortly and provide feedback or release.

**Comment by amotl** [comment]
@gsong: Excellent, thanks!

**Comment by gsong** [comment]
@amotl I'm working through the conflicts (simple) and some refactoring right now, so don't worry about pushing additional code to this branch. I'll let you know as soon as the next version is released with this feature (should be today or tomorrow).

**Comment by amotl** [comment]
Dear @gsong,

thanks a bunch for working on the update. I recognize what you are doing there. The commit today was just a slight update for the `family-legal` test where I spotted a typo as it would redundantly run the `family-biblio` test I added for covering the regression.

Thanks again!

Cheers,
Andreas.

**Comment by gsong** [comment]
@amotl Can you take a look at https://github.com/55minutes/python-epo-ops-client/tree/ip-tools-fix-family to make sure your fix made it in? I'm not sure exactly what you changed.

**Comment by amotl** [comment]
I can confirm the little fix is in [1], thanks!

[1] https://github.com/55minutes/python-epo-ops-client/blob/ip-tools-fix-family/tests/test_api.py#L37-L42

**Comment by gsong** [comment]
👍

**Comment by gsong** [comment]
@amotl This has been released: https://pypi.org/project/python-epo-ops-client/

**Comment by amotl** [comment]
Thank you so much [1] and keep up the good work!

[1] https://meta.ip-tools.org/t/bibliographic-data-missing-from-ops-family-response/161/6

**Pull request closed without merging**
